myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns =[
    path('', views.cart_detail, name='cart_detail'),
    path('add/', views.cart_add, name='cart_add'),
    path('remove/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/shop/urls.py
from django.contrib import admin
from django.urls import path
from myshop.shop import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'
urlpatterns = [
    path('', views.MainPage.as_view(), name = 'home'),
    path('product/<slug:product_slug>/', views.ShowProduct.as_view(), name = 'product'),
    path('shop/', views.ShopPage.as_view(), name = 'shop'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('addproduct/', views.AddProduct.as_view(), name='addproduct'),
    path('category/<slug:cat_slug>/', views.CategoryUpdateView.as_view(), name='category_list'),
    path('category/<slug:cat_slug>/', views.ProductCategory.as_view(), name='category'),
    path('category-one/<int:pk>', views.CategoryDetailView.as_view(), name='category_one'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from .shop import views
from django.conf import settings

from .shop.api_views import ProductViewSet, CategoryViewSet

router = routers.DefaultRouter()
router.register('product', ProductViewSet)
router.register('category', CategoryViewSet)

app_name = 'shop'
urlpatterns = [
    path('', include('myshop.shop.urls', namespace='shop')), #views.MainPage.as_view()),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/v0/', include(router.urls))

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns

myshop/cart/models.py
from django.db import models

# Create your models here.
from decimal import Decimal
from django.conf import settings
from myshop.shop.models import Product

class Cart(object):
    def __init__(self, request):
        # Инициализируем корзину
        self.session = request.session
        cart = self.session.get(settings.CART_SESSION_ID)
        if not cart:
            cart = self.session[settings.CART_SESSION_ID] = {}
        self.cart = cart

    def add(self, product, quantity=1, update_quantity=False):
        # Добавить продукт в корзину или обновить его количество
        product_id = str(product.id)
        if product_id not in self.cart:
            self.cart[product_id] = {'quantity': 0, 'price': str(product.price)}
        if update_quantity:
            self.cart[product_id]['quantity'] = quantity
        else:
            self.cart[product_id]['quantity'] += quantity
        self.seve()

    def save(self):
        # Обновление сессии cart
        self.session[settings.CART_SESSION_ID] = self.cart
        # Отметить сеанс как "измененный", чтобы убедиться, что он сохранен
        self.session.modified = True

    def remove(self, product):
        # Удаление товара из корзины
        product_id = str(product.id)
        if product_id in self.cart:
            del self.cart[product_id]
            self.save()

    def __iter__(self):
        # Перебор элементов в корзине и получение продуктов из БД
        product_ids = self.cart.keys()
        products = Product.objects.filter(id__in = product_ids)
        for product in products:
            self.cart[str(product.id)]['product'] = product

        for item in self.cart.values():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']
            yield item

    def __len__(self):
        # Подсчет всех товаров в корзине
        return sum(item['quantity'] for item in self.cart.values())

    def get_total_price(self):
        # Подсчет стоимости товаров в корзине
        return sum(Decimal(item['price']) * item['quantity'] for item in self.cart.values())

    def clear(self):
        # Удаление корзины из сесии
        del self.sesiion[settings.CART_SESSION_ID]
        self.session.modified = True

myshop/myshop/shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class ActiveManager(models.Manager):
    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_active=True)

class IsActiveMixin(models.Model):
    objects = models.Manager()
    active_objects = ActiveManager()
    is_active = models.BooleanField(default= False)

    class Meta:
        abstract = True

class Category(IsActiveMixin, models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name='URL')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

class Product(IsActiveMixin, models.Model):
    #cat = models.ForeignKey('Category',on_delete=models.PROTECT)
    title = models.SlugField(max_length=200)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', null = True, blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    product_cat = models.ManyToManyField(Category)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('prods', kwargs={'prods_slug': self.slug})

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices = PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/myshop/shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Product

class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password2']

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class AddProductForm(forms.ModelForm):
    product_name = forms.CharField(label = 'Название продукта')

    class Meta:
        model = Product
        fields = '__all__'

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from myshop.shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html')

myshop/myshop/shop/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.http import HttpResponse
from django.utils.functional import cached_property
from .models import Category, Product
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from .forms import LoginForm, RegisterUserForm, AddProductForm, RegisterUserForm
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from .utils import DataMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

class MainPage(DataMixin, ListView):
    model = Product
    template_name = 'myshop/index.html'
    context_object_name = 'prods'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title= "Главная страница интернет-магазина")
        context = dict(list(context.items()) + list(c_def.items()))

        list_product = Product.active_objects.all().prefetch_related('product_cat').only('name', 'price', 'image')
        paginator = Paginator(list_product, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        context['list_product'] = products

        return context

    def get_queryset(self):
        return Product.objects.filter(available = True)

class ShopPage(ListView):
    model = Product
    template_name = 'myshop/shop.html'
class CartPage(DetailView):
    #model =
    template_name = 'myshop/cart.html'
class CheckoutPage(FormView):
    template_name = 'myshop/checkout.html'
class ShowProduct(DataMixin, DetailView):
    model = Product
    template_name = 'myshop/single-product.html'
    slug_url_kwarg = 'product_slug'
    context_object_name = 'product'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=context['products'])
        return dict(list(context.items()) + list(c_def.items()))
    def get_object(self, **kwargs):
        object = super().get_object(**kwargs)
        return object

class AddProduct(LoginRequiredMixin, DataMixin, CreateView):
    form_class = AddProductForm
    template_name = 'myshop/product_add.html'
    success_url = reverse_lazy('home')
    login_url = reverse_lazy('home')
    #raise_exception = True #запрет доступа к странице либо декоратор для функции @login_required

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Добавление товара')
        return dict(list(context.items()) + list(c_def.items()))

class ProductCategory(DataMixin, ListView):
    model = Category
    template_name = 'myshop/index.html'
    context_object_name = 'prods'
    allow_empty = False
    def get_queryset(self):
        return Product.objects.filter(cat__clug=self.kwargs['cat_slug'], is_published=True)
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Категория - ' + str(context['products'][0].cat),
                                      cat_selected=context['products'][0].cat_id)
        return dict(list(context.items()) + list(c_def.items()))

class CategoryDetailView(DetailView):
    model = Category
    template_name = 'myshop/single-product.html'

class CategoryUpdateView(UpdateView):
    template_name = 'myshop/category_update.html'
    model = Category
    success_url = reverse_lazy('myshop:category_list')

'''
class CategoryDeleteView(DeleteView):
    template_name = 'myshop/category_delete.html'
    model = Category
    success_url = reverse_lazy('myshop:category_list')

class CategoryCreateView(CreateView):
    fields = '__all__'
    template_name = 'myshop/category_create.html'
    model = Category
    success_url = reverse_lazy('myshop:category_list') 
'''

class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'myshop/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Регистрация")
        return dict(list(context.items()) + list(c_def.items()))
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')

class LoginUser(DataMixin, LoginView):
    form_class = AuthenticationForm
    template_name = 'myshop/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('home')

def logout_user(request):
    logout(request)
    return redirect('login')

class PermissionMixin:
    def test_func(self):
        return self.request.user.is_superuser
    def handle_no_permission(self):
        return HttpResponseRedirect(reverse('shop:index'))

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'myshop/single-product.html', {'product': product,
                                                          'cart_product_form': cart_product_form})

myshop/myshop/shop/templates/myshop/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Интернет-магазин</title>

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
    {% load static %}
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

  </head>
  <body>
    <div class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="user-menu">
                        <ul>
                            {% if user.is_authenticated %}
                            <li class="last">{{user.username}} <a href="{% url 'users:logout' %}">Выйти</a></li>
                            {% else %}
                            <li class="last"><a href="{% url 'users:register' %}"><i class="fa fa-user"></i> Регистрация</a></li>
                            <li class="last"><a href="{% url 'users:login' %}"><i class="fa fa-user"></i> Логин</a></li>
                            {% endif %}
                            <li><a href="#"><i class="fa fa-user"></i> Мой аккаунт</a></li>
                            <li><a href="#"><i class="fa fa-heart"></i> Wishlist</a></li>
                            <li><a href=""><i class="fa fa-user"></i> Корзина</a></li>
                            <li><a href=""><i class="fa fa-user"></i> Checkout</a></li>

                        </ul>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="header-right">
                        <ul class="list-unstyled list-inline">
                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">валюта  :</span><span class="value">RUB </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">RUB</a></li>
                                    <li><a href="#">EUR</a></li>
                                    <li><a href="#">USD</a></li>
                                </ul>
                            </li>

                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">язык :</span><span class="value">Русский </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Русский</a></li>
                                    <li><a href="#">English</a></li>
                                    <li><a href="#">German</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End header area -->

    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><a href="./"><img src="{% static 'img/logo.png' %}"></a></h1>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="cart">
                        {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                                Корзина:
                                <a href="{% url 'cart:cart_detail' %}">
                                    {{ total_items }} item{{ total_items|pluralize }},
                                    ${{ cart.get_total_price }}
                                </a>
                            {% else %}
                                0
                            {% endif %}
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End site branding area -->

    {% block content %} {% endblock %}
    <div class="mainmenu-area">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Навигация</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="index.html">Главная</a></li>
                        <li><a href="shop.html">Каталог</a></li>
                        <li><a href="single-product.html">Товар</a></li>
                        <li><a href="cart.html">Корзина</a></li>
                        <li><a href="checkout.html">Заказ</a></li>
                        <li><a href="#">Категории</a></li>
                        <li><a href="#">Другое</a></li>
                        <li><a href="#">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div> <!-- End mainmenu area -->


    <div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2>Brand<span>Brand</span></h2>
                        <p>Some text</p>
                        <div class="footer-social">
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Пользовательская Навигация </h2>
                        <ul>
                            <li><a href="#">Мой аккаунт</a></li>
                            <li><a href="#">История заказов</a></li>
                            <li><a href="#">Wishlist</a></li>
                            <li><a href="#">Vendor contact</a></li>
                            <li><a href="#">Front page</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Категории</h2>
                        <ul>
                            <li><a href="#">Смартфоны</a></li>
                            <li><a href="#">Аксессуары</a></li>
                            <li><a href="#">LED TV</a></li>
                            <li><a href="#">Компьютеры</a></li>
                            <li><a href="#">Гаджеты</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-newsletter">
                        <h2 class="footer-wid-title">Newsletter</h2>
                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                        <div class="newsletter-form">
                            <form action="#">
                                <input type="email" placeholder="Type your email">
                                <input type="submit" value="Subscribe">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer top area -->

    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                        <p>&copy; 2023</p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="footer-card-icon">
                        <i class="fa fa-cc-discover"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-paypal"></i>
                        <i class="fa fa-cc-visa"></i>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer bottom area -->

    <!-- Latest jQuery form server -->
    <script src="https://code.jquery.com/jquery.min.js"></script>

    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- jQuery sticky menu -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>

    <!-- jQuery easing -->
    <script src="{% static 'js/jquery.easing.1.3.min.js' %}"></script>

    <!-- Main Script -->
    <script src="{% static  'js/main.js' %}"></script>

    <!-- Slider -->
    <script type="text/javascript" src="{% static 'js/bxslider.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/script.slider.js' %}"></script>
  </body>
</html>

myshop/myshop/shop/templates/myshop/category_list.html
{% extends "shop/myshop/templates/base.html" %}
{% block content %}
<ul>
    {% for cats in categories %}
        <li>
            <a href = "{%url 'categories:category_one' pk=cats.pk %}">{{cats.category_name}}</a>
        </li>
    {% endfor %}
</ul>
<a href = "{%url 'categories:category_create' %}">Создать категорию</a>

{% endblock %}

myshop/myshop/shop/templates/myshop/category_update.html
{% extends "shop/myshop/templates/base.html" %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

myshop/myshop/shop/templates/myshop/product_add.html
{% extends "myshop/base.html" %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for fields in form %}
            <p>{{fields.label_tag}}</p>
            <hr>
            {% for error in field.errors %}
                {{error}}
            {% endfor %}
            <p>{{fields}}</p>
        {% endfor %}
        <button type="submit">Добавить товар</button>
    </form>
{% endblock %}

myshop/myshop/shop/templates/myshop/shop.html
{% extends "myshop/base.html" %}
{% block content %}

<div class="product-big-title-area">
    <div class="container">
         <div class="row">
              <div class="col-md-12">
                  <div class="product-bit-title text-center">
                      <h2>Каталог товаров</h2>
                  </div>
              </div>
         </div>
    </div>
</div>
    
<h3>Все товары</h3>
<div class="container">
    <div class="row">
        {% for product in products.all %}
            <a href="{% url 'products.product' id=product.id %}">
                <img src="{{product.product.img.url}}" alt="Image" class="img-fluid rounded"></a>
            <div class="excerpt">
                <h2><a href="{% url 'products:product' id=product.id %}">{{product.product_name}}</a></h2>
                <div class="post-meta align-items-center text-left clearfix">
                    <span>&nbsp;-&nbsp; {{product.product_date}}</span>
                </div>
            </div>
        {% endfor %}

    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>

{% endblock %}